### ISSUE TITLE
install warm deps is currently bugged

### ISSUE THREAD

**Issue by wild-kard** [wild-kard/arctica#104]
throws fatal error on login.

Closer look at the error message reveals that it is a disk full error, and this is happening when attempting to download and install ubuntu system security updates (among other things).

Currently need to find a solution to this problem, the easy answer (although painful for initial setup) is to increase the size of the image (which allows for more space in the persistent storage directory on each HW. 

The less easy answer is potentially changing how the filesystem gets flashed onto each HW.

**Comment by BenWestgate** [comment]
You will also save hours of flashing time going this route.

**Comment by wild-kard** [comment]
Resolved
https://github.com/wild-kard/arctica/commit/b35ab4cd6bcaebf50f1afefc0e9bec4901b0638d
