### ISSUE TITLE
During initial installation user will not be warned if they fail to remove and replace a previously flashed card or reinsert a previously flashed card

### ISSUE THREAD

**Issue by wild-kard** [wild-kard/arctica#15]
It is possible for us to fix the latter issue by looking for config.txt at /media/$user/writable1/upper/home/
(Note: writable1 occurs here because writable is already mounted at media to be used for the iso)

However, fixing the former issue is more difficult because the file system does not automount after mkusb and requires the user remove and reinsert the device. Thus, it is more difficult to issue a warning to the user because we cannot as easily access the file system.

It may be possible to manually mount the file system after mkusb which would potentially allow us to check for a config.txt and warn the user if the card they are attempting to flash has already been setup as an arctica device... in which case we would prompt with an additional dialog box to confirm user action.

**Comment by BenWestgate** [comment]
Why not log the UUIDs for the previously flashed raw devices and warn if they're the same.

`udevadm info -q all -n /dev/sda`

Will get the device UUID even if it's not mounted or has been ejected with `sudo eject /dev/sda` it won't work if the device has been powered off `udisksctl power-off -b /dev/sda` which is the equivalent of removing it.

**Comment by wild-kard** [comment]
> Why not log the UUIDs for the previously flashed raw devices and warn if they're the same.
> 
> `udevadm info -q all -n /dev/sda`
> 
> Will get the device UUID even if it's not mounted or has been ejected with `sudo eject /dev/sda` it won't work if the device has been powered off `udisksctl power-off -b /dev/sda` which is the equivalent of removing it.

Great Idea

**Comment by BenWestgate** [comment]
You can get the device name of the most recently inserted device from udisks monitor.  You can call the daemon with udisksctl monitor.

**Comment by BenWestgate** [comment]
Did you do this?

I need to do something similar for https://github.com/BenWestgate/Bails

**Comment by wild-kard** [comment]
Front end now provides adequate feedback 
https://github.com/wild-kard/arctica-frontend/commit/91211b069e3e9c61c75bc072c4806cfb606444db

Backend: create_bootable_usb function now properly errors out when duplicate file paths are detected that indicate flashed arctica media
https://github.com/wild-kard/arctica/commit/673f0599c9d89ff8fb79402dacccd25f59e300be
