### ISSUE TITLE
CD/DVD drive will sometimes not automatically mount on ubuntu live system

### ISSUE THREAD

**Issue by wild-kard** [wild-kard/arctica#18]
This obviously breaks application features due to heavy reliance on RW CDs to pass data between sessions. 

This can be worked around by manually creating the mountpoint with

`sudo mkdir /media/ubuntu/CDROM`

And then manually mounting the disc with

`sudo mount /dev/sr0 /media/ubuntu/CDROM`

Suggested fix is to check if the mountpoint already exists when the user has confirmed that a CD is inserted, and if not, create the mount point and mount the disc.

**Comment by wild-kard** [comment]
I have partially rectified this with a hamfisted fix which attempts to mount /dev/sr0 to a manually created /media/$USER/CDROM directory here inside the read_cd function.

https://github.com/wild-kard/arctica/commit/f78b513157ebdbdeef7548893382904237d5d908

Need to implement more fixes however, potentially also inside of copy_cd_to_ramdisk function.

**Comment by wild-kard** [comment]
Further fixing here
https://github.com/wild-kard/arctica/commit/ca5f5d67cf995b5bedd1f77f8013311154087105

I'm still not very happy with this solution. Previously I was only running into this issue with CDs not auto-mounting when inserted occasionally, however, with a recent round of testing, all 7 cards are consistently not automounting the CD on two separate computers. 

This leads me to believe it is a bug created within the ubuntu iso itself and not one of the physical hardware. 

Keeping this issue open for now but downgrading it to minor but it is technically resolved for now.

**Comment by BenWestgate** [comment]
https://askubuntu.com/questions/25759/auto-mount-cd-dvd-drive-to-single-specific-mount-point-every-time

fstab is the solution for automatic mounting of devices, including DVD/CD.

**Comment by wild-kard** [comment]
Closing this issue as I believe recent changes to how CDs are handled within app should mitigate this problem entirely.
