### ISSUE TITLE
[Major] Bitcoin core shutting down during initial sync. 

### ISSUE THREAD

**Issue by wild-kard** [wild-kard/arctica#22]
Message says insufficient space during chainstate flush. Perhaps a large persistent partition is needed on the sd card?

Temporary fix is to run `bitcoin-cli stop`

try starting bitcoind with `./bitcoind --walletdir=/home/ubuntu/.bitcoin --datadir=/media/ubuntu/$UUID/home/ubuntu/.bitcoin`

Note: the above fix is a potential privacy leak. Move debug log to tmp to avoid. 

`ln -s /tmp/debug.log /media/ubuntu/$UUID/home/ubuntu/.bitcoin/debug.log`

**Comment by wild-kard** [comment]
An update: 

I have just confirmed that completing IBD while booted into the internal machine Operating System, performing a clean shutdown of Bitcoin Daemon, and then booting into SD 1 allows for a proper sync without the memory limitation of the live system.


Next test will be performing IBD on SD 1 with a larger writable partition, the drawback here is that doubling the size of the image flashed onto each SD card doubles the mkusb time. My most recent test came back at 789s mkusb operation with a 10GB fallocate, which is approximately double the flash time of a 5GB fallocate.

**Comment by wild-kard** [comment]
This issue has been resolved with the following commit https://github.com/wild-kard/arctica/commit/6735d6b1177eb83ac0b8aa81685973354cfcf202 which increases the memory allocation to the USB image from 5GB to 7GB. This allows for a larger persistent partition on the usb image providing enough disc memory for the debug.log to grow during IBD.

**Comment by BenWestgate** [comment]
You could also have just turned the debug.log off with `-nodebuglog`

**Comment by wild-kard** [comment]
> You could also have just turned the debug.log off with `-nodebuglog`

Would that cause any consequences?

**Comment by BenWestgate** [comment]
Not having a debug.log to troubleshoot with.  You might be reading from it elsewhere in your program to see the `progress=` field, but you can use a rpc command to know when IBD has completed.
