### ISSUE TITLE
Ubuntu enables memory swap by default

### ISSUE THREAD

**Issue by epiccurious** [wild-kard/arctica#41]
When memory swapping, the system writes volatile memory in RAM to non-volatile disk storage.

In Ubuntu 22, [the system defaults to a `swapiness` of 60](https://askubuntu.com/questions/103242/is-it-safe-to-turn-swap-off-permanently).
```
$ cat /proc/sys/vm/swappiness
60
```

60 `swappiness` means, as I understand it, that swap files will be created when the system uses more than 40% of the RAM.

When Arctica is dealing with sensitive data in RAM, the swap should be disabled.

To disable for just this boot session, use `sudo swapoff -a`.

To permanently disable swap for this Ubuntu installation, [swap should be disabled in `fstab`](https://askubuntu.com/questions/214805/how-do-i-disable-swap).

Also, need to consider what drawbacks there are for disabling swap. For example, swap during the Bitcoin Core IBD is probably beneficial for speeding up the process, especially for 4GB and 8GB RAM systems.

Might also make sense to consider reducing Bitcoin Core's `dbcache` after IBD when disabling swap.

**Comment by wild-kard** [comment]
Resolved with the following commit
https://github.com/wild-kard/arctica/commit/7b65e70ea871cc844df009628834795ad4cc9cbb
