### ISSUE TITLE
User should be able to do a full recovery in an offline state

### ISSUE THREAD

**Issue by wild-kard** [wild-kard/arctica#45]
Ideally user should be able to do a complete recovery from an offline state. CDs should back up absolutely everything essential to do a full recovery (and potentially even create a new Arctica Wallet from scratch offline)

This includes
Arctica Binary
Dependencies
Scripts Dir (if applicable)
Xpubs & Xprivs (if recovering)
Descriptors (if recovering)
decryption shards (if recovering)

Edit:

This may not be possible. Atleast, it may not be possible to flash a new USB with a bootable ubuntu ISO without an online connection, building that iso requires some dependencies and compiling.

**Comment by wild-kard** [comment]
This is not possible. 

I want the user to download the latest arctica binary to restore from a backup CD, this is because they will need to build a new bootable ubuntu iso so it's best performed on a computer booted regularly without any arctica media inserted. 

This will require an internet connection to obtain all of the dependencies for building and flashing the bootable HW

**Comment by BenWestgate** [comment]
dependencies dont fit on the DVD?

**Comment by wild-kard** [comment]
The dependencies for building the iso and flashing it to a usb stick are different than the dependencies for running the app and it's features.

The dependencies necessary for the operation of the HW are stored on the backup (genisoimage, libqrencode, qrencode, ssss, tor, wodim, & xclip).

The others are only necessary for building the iso and flashing ubuntu (qemu-system-x86, qemu-kvm, libvirt-clients, libviert-daemon-system, bridge-utils, universe repo & ppa:mkusb/ppa, mkusb, and usb-pack-efi). That's a lot to include on every backup disc, but maybe it's theoretically possible? I would have to check the space requirements. 

But I don't think you're going to want the user flashing an image while booted into a linux live system running in ram anyway so it makes more sense to me to have the user do it fresh.

**Comment by wild-kard** [comment]
No, the ubuntu iso is 5GB and my CDs have a 700MB capacity.

The DVD is a backup of sensitive material and application state.

**Comment by BenWestgate** [comment]
Why isn't the DVD bootable so you can sign with it when the flash devices inevitably bit rot in a year or two?

**Comment by wild-kard** [comment]
That's actually a very good idea. I haven't actually done any testing with DVDs yet so I hadn't considered it, in theory it's all the same as CD just with higher capacity?

**Comment by BenWestgate** [comment]
> That's actually a very good idea. I haven't actually done any testing with DVDs yet so I hadn't considered it, in theory it's all the same as CD just with higher capacity?
> 
> 
> 
> 8.5GB DVDs would be pretty tight...especially for one of the warm wallets...but it would probably be able to handle signer functions as a bootable cold wallet
> 
> 
> 
> This is certainly not something I can promise anytime soon, but I will certainly keep this issue open maybe for the V2. 
> 
> 

Besides higher capacity, DVDs read and write faster and are more resistant to scratches.

DVD is 4.7GB capacity there's dual layer ones with 8.5GB, if it's a totally offline restore I'd exclude the ubuntu updates to help it fit.

DVD is unsuitable for operating a warm wallet because it can't be randomly rewritten, you'd cause address reuse. Signing devices only.
