### ISSUE TITLE
[Critical Security] Make certain apt packages available at initial flash

### ISSUE THREAD

**Issue by wild-kard** [wild-kard/arctica#6]
Wodim and libgfshare-bin are required debian packages for reading from and writing to CDs/DvDs and unpacking the encrypted directories where private keys are stored on each SD card. 

In order for SD cards to be offline only, these packages need to be included with the persistent-ubuntu.iso that get's flashed onto all 7 SD cards, created by init-iso.sh.

For now, the packages must be installed on each SD card and is included in the create-setup-cd.sh script which is automatically run when starting arctica while booted into SD 1. 

Edit 1 11/17/2022 - consider copying all binaries from the local disk and then using chroot to access the ubuntu iso and install deb packages

**Comment by wild-kard** [comment]
sudo add-apt-repository -y universe


sudo apt update


sudo apt install -y wodim


sudo apt install ssss

**Comment by epiccurious** [comment]
From a fresh install of Ubuntu Desktop 22 LTS:

> `wodim` also has one additional dependency `genisoimage`
/usr/bin/wodim
/usr/bin/genisoimage

> `ssss` has no additional dependencies

We can download the .deb files with
`apt download wodim=9:1.1.11-3.2ubuntu1 genisoimage=9:1.1.11-3.2ubuntu1 ssss=0.5-5`. Then use `losetup` to attach the iso and mount the rootfs partition. Then copy the `.deb`s.

**Comment by wild-kard** [comment]
This issue has been resolved with the following commit
https://github.com/wild-kard/arctica/commit/94f57bbeaf61aa6b42ae1a7213a944626dcf1a60

This change obtains dependencies during init_iso and preloads the required .deb packages onto each SD card. The .deb files are then installed at first boot, without requiring an internet connection.
